### PR TITLE
Add a configuration paragraph to setup the server

### PR DESCRIPTION
**Pull request by bbougon**
I did add 2 paragraphs about configuration to setup the project dir and add the log file `.sensei.log` into user home directory (btw, not having this file throws a 500).
Thanks for the README, it helped much ;)

### CODE REVIEW

**Comment by bbougon** [comment]
Add a config.js file in which you have a user defined at build time.
Not sure the way i did it is good tho

**Comment by bbougon** [comment]
I have unwillingly remove dom import, sorry

**Comment by bbougon** [comment]
This last commit fix an issue from the seconde one.

**Review by abailly — APPROVED** [review]
Thanks a lot Bertrand! This is temporary anyway but good to have should other people want to test this early version :)

**Pull request merged**
